In [16]:
import time
import pynput 

In [50]:
from pynput import keyboard

err = 0
charac = 0
t0 = time.time()
t1 = 0.0
err = 0
char = 0

def on_press(key):
    #global t0
    global err
    global char   
    
    
    try:
        print('alphanumeric key {0} pressed'.format(
            key.char))
        if (key == keyboard.Key.backspace or key == keyboard.Key.delete):
            err+=1
            #print("***********************")
        else:
            char+=1
            #print("***********************")
    except AttributeError:
        if (key == keyboard.Key.backspace or key == keyboard.Key.delete):
            err+=1
            #print("***********************")
        print('special key {0} pressed'.format(
            key))

def on_release(key):
    global t1
    print('{0} released'.format(
        key))
    if key == keyboard.Key.esc:
        # Stop listener
        t1 = time.time()
        return False

# Collect events until released
with keyboard.Listener(
        on_press=on_press,
        on_release=on_release) as listener:
    listener.join()


listener = keyboard.Listener(
    on_press=on_press,
    on_release=on_release)
listener.start()

#print(t1)
#print(t0)
#print(err)
#print(char)
minutes = (t1-t0)/60.0
err_rate = err/minutes
char_rate = char/minutes
print(minutes)
print(char_rate)
print(err_rate)




Key.enter released
Key.shift_r released
special key Key.shift pressed
alphanumeric key M pressed
'M' released
Key.shift released
special key Key.shift pressed
alphanumeric key U pressed
'U' released
alphanumeric key M pressed
'M' released
alphanumeric key B pressed
alphanumeric key A pressed
'B' released
alphanumeric key I pressed
'A' released
'I' released
Key.shift released
special key Key.shift pressed
special key Key.shift_r pressed
Key.shift released
alphanumeric key : pressed
':' released
Key.shift_r released
special key Key.space pressed
Key.space released
special key Key.shift pressed
alphanumeric key T pressed
'T' released
Key.shift released
alphanumeric key w pressed
alphanumeric key o pressed
'w' released
'o' released
special key Key.space pressed
Key.space released
alphanumeric key d pressed
'd' released
alphanumeric key a pressed
'a' released
alphanumeric key y pressed
'y' released
alphanumeric key s pressed
's' released
special key Key.space pressed
Key.space released
alph

alphanumeric key s pressed
's' released
alphanumeric key t pressed
't' released
alphanumeric key a pressed
'a' released
alphanumeric key f pressed
'f' released
alphanumeric key f pressed
'f' released
special key Key.space pressed
Key.space released
alphanumeric key o pressed
'o' released
alphanumeric key f pressed
'f' released
special key Key.space pressed
Key.space released
alphanumeric key m pressed
alphanumeric key a pressed
'm' released
'a' released
alphanumeric key l pressed
'l' released
alphanumeric key l pressed
'l' released
alphanumeric key s pressed
's' released
special key Key.space pressed
Key.space released
alphanumeric key t pressed
alphanumeric key o pressed
't' released
'o' released
special key Key.space pressed
Key.space released
alphanumeric key e pressed
alphanumeric key n pressed
'e' released
'n' released
alphanumeric key t pressed
alphanumeric key e pressed
't' released
'e' released
alphanumeric key r pressed
'r' released
special key Key.space pressed
Key.space rele

In [9]:
import csv

with open('user_profile.csv', 'a') as log_file:
        writer = csv.writer(log_file)
        writer.writerow([char_rate, err_rate])
        

# Using the Data for Analysis (Processing)

In [33]:
import pandas as pd

df=pd.read_csv('user_profile.csv')
print(df)

     char_rate   err_rate  Admin
0   112.111190   2.822021      1
1   110.100000  15.000000      0
2   115.471228   3.633710      1
3   118.828080   3.419513      1
4   120.755437   5.275723      1
5    98.056000   0.199000      0
6   121.145659   4.450249      1
7   122.108388   2.787863      1
8   129.365000   3.693000      0
9   119.929182   1.961459      1
10  112.905846   6.409502      1
11  128.928384   4.112162      1
12  123.172126   3.421448      1


In [31]:
print("Average Characters per Minute(CPM): ",df['char_rate'].mean())
avg_cpm = df['char_rate'].mean()
min_cpm = df['char_rate'].min()
max_cpm = df['char_rate'].max()
print("Min CPM                           : ", df['char_rate'].min())
print("Max CPM                           : ", df['char_rate'].max())

Average Characters per Minute(CPM):  119.53555199400418
Min CPM                           :  112.11119026909498
Max CPM                           :  128.92838419385015


In [32]:
avg_epm = df['err_rate'].mean()
min_epm = df['err_rate'].min()
max_epm = df['err_rate'].max()
print("Average Error Rate[EPM]: ",df['err_rate'].mean())
print("Min EPM                : ", df['err_rate'].min())
print("Max EPM                : ", df['err_rate'].max())

Average Error Rate[EPM]:  3.8293649327689487
Min EPM                :  1.9614585781098017
Max EPM                :  6.4095021680137245


In [3]:
import numpy as np
input_3 = df.to_numpy()
input_3

array([[112.11119027,   2.82202081,   1.        ],
       [110.1       ,  15.        ,   0.        ],
       [115.47122792,   3.63370997,   1.        ],
       [118.82807986,   3.41951309,   1.        ],
       [120.75543699,   5.27572298,   1.        ],
       [ 98.056     ,   0.199     ,   0.        ],
       [121.14565946,   4.45024871,   1.        ],
       [122.10838793,   2.78786274,   1.        ],
       [129.365     ,   3.693     ,   0.        ],
       [119.92918163,   1.96145858,   1.        ],
       [112.90584588,   6.40950217,   1.        ],
       [128.92838419,   4.11216235,   1.        ],
       [123.17212581,   3.42144794,   1.        ]])

In [15]:

import pandas as pd
from sklearn.linear_model import Perceptron



if __name__ == "__main__":
  
    data = pd.read_csv('user_profile.csv').values

    # Extract the feature columns and outcome response
    # into appropriate variables
    X = data[:, 0:2]
    y = data[:, 2]

    # Create and fit a perceptron model (with reproducible
    # random seed)
    model = Perceptron(random_state=1)
    model.fit(X, y)

    # Output the (in sample) mean accuracy score
    # of the classification
    print("%0.3f" % model.score(X, y))

0.846


In [23]:
from sklearn.svm import SVC
clf = SVC()
clf.fit(X,y) 
Decision_Function = clf.decision_function(X)
print('Output of Decision Function is:', Decision_Function)
predict = clf.predict(X)
print('Prediction for x_test from classifier is:', predict)

Output of Decision Function is: [0.99843794 0.97217545 1.00000002 1.00254842 1.         0.9818018
 1.0016676  1.00494578 1.00323728 1.00563988 0.99260991 1.00261257
 1.00405706]
Prediction for x_test from classifier is: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
from sklearn.linear_model import SGDClassifier

In [7]:
 data = pd.read_csv('user_profile.csv').values
X = data[:, 0:2]
y = data[:, 2]
clf = SGDClassifier(loss="hinge", penalty="l2", max_iter=40)
clf.fit(X, y)
SGDClassifier(max_iter=40)

SGDClassifier(max_iter=40)

In [12]:
clf.predict([[119, 1256]])

array([0.])

In [49]:
weights = clf.coef_
print("Weights are : ",weights)

Weights are :  [[ 559.32372303 -889.34828705]]


In [14]:
clf.intercept_

array([-18.29835198])

# Testing

In [47]:
from pynput import keyboard

err = 0
charac = 0
t0 = time.time()
t1 = 0.0
err = 0
char = 0

def on_press(key):
    #global t0
    global err
    global char   
    
    
    try:
        print('alphanumeric key {0} pressed'.format(
            key.char))
        if (key == keyboard.Key.backspace or key == keyboard.Key.delete):
            err+=1
            #print("***********************")
        else:
            char+=1
            #print("***********************")
    except AttributeError:
        if (key == keyboard.Key.backspace or key == keyboard.Key.delete):
            err+=1
            #print("***********************")
        print('special key {0} pressed'.format(
            key))

def on_release(key):
    global t1
    print('{0} released'.format(
        key))
    if key == keyboard.Key.esc:
        # Stop listener
        t1 = time.time()
        return False

# Collect events until released
with keyboard.Listener(
        on_press=on_press,
        on_release=on_release) as listener:
    listener.join()

# ...or, in a non-blocking fashion:
listener = keyboard.Listener(
    on_press=on_press,
    on_release=on_release)
listener.start()

#print(t1)
#print(t0)
#print(err)
#print(char)
minutes = (t1-t0)/60.0
err_rate = err/minutes
char_rate = char/minutes
print(minutes)
print(char_rate)
print(err_rate)

Key.enter released
special key Key.shift pressed
alphanumeric key M pressed
'M' released
alphanumeric key U pressed
'U' released
alphanumeric key M pressed
'M' released
alphanumeric key B pressed
'B' released
alphanumeric key A pressed
alphanumeric key I pressed
'A' released
'I' released
Key.shift released
special key Key.shift_r pressed
alphanumeric key : pressed
Key.shift_r released
';' released
special key Key.space pressed
Key.space released
special key Key.shift pressed
alphanumeric key T pressed
'T' released
Key.shift released
alphanumeric key w pressed
alphanumeric key o pressed
'w' released
'o' released
special key Key.space pressed
Key.space released
alphanumeric key d pressed
'd' released
alphanumeric key a pressed
alphanumeric key y pressed
'a' released
'y' released
alphanumeric key s pressed
's' released
special key Key.space pressed
Key.space released
alphanumeric key a pressed
'a' released
alphanumeric key f pressed
alphanumeric key t pressed
'f' released
alphanumeric key

'o' released
alphanumeric key f pressed
'f' released
special key Key.space pressed
alphanumeric key t pressed
Key.space released
't' released
alphanumeric key h pressed
'h' released
alphanumeric key e pressed
'e' released
special key Key.space pressed
Key.space released
alphanumeric key m pressed
alphanumeric key a pressed
'm' released
alphanumeric key l pressed
'a' released
'l' released
alphanumeric key l pressed
'l' released
alphanumeric key s pressed
's' released
special key Key.space pressed
Key.space released
alphanumeric key t pressed
alphanumeric key o pressed
't' released
'o' released
special key Key.space pressed
Key.space released
alphanumeric key e pressed
alphanumeric key n pressed
'e' released
'n' released
alphanumeric key t pressed
't' released
alphanumeric key r pressed
'r' released
special key Key.space pressed
Key.space released
alphanumeric key e pressed
'e' released
alphanumeric key v pressed
'v' released
alphanumeric key n pressed
'n' released
special key Key.backsp

In [37]:
clf.predict([[char_rate,err_rate]])

array([1.])

In [48]:
if(char_rate >= min_cpm and char_rate<max_cpm):
    clf.predict([[char_rate,err_rate]])
    if(int(clf.predict([[char_rate,err_rate]]) == 1)):
        print("User is Chandni")
    else:
        print("User is UNKOWN")
else:
    print("User is UNKNOWN")

User is Chandni
